version: '3.3'
services:
  django-rest:
    build: .
    container_name: django-rest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8001:8000
    networks:
      - rest-network
    environment:
      DB_NAME: db
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_HOST: mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      rest-network:
        aliases:
          - mysql
    ports:
      - 3307:3306      
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: db  
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10    

networks:
  rest-network: